### PR TITLE
Update curator to 5.7.6

### LINKED ISSUE #38: 5.7 relase?
Curator 5.6 doesn't support ES 7.X, might be worth pushing one.

### PR DESCRIPTION
**Pull request by eyalzek**
Fixes #38

### CODE REVIEW

**Comment by renan** [comment]
@bobrik Would you please merge this pull request? :)

**Comment by eyalzek** [comment]
@renan check this out in the meantime: https://github.com/elastic/curator/issues/528#issuecomment-490132387

**Comment by renan** [comment]
@eyalzek I also created a topic in their Discuss-thingy but they aren't interested in maintaining an officially published image, see: https://discuss.elastic.co/t/missing-few-official-docker-images/160138

**Comment by eyalzek** [comment]
Yeah I saw that, but if you need to run a docker image for curator 5.7.6, `untergeek/curator:5.7.6` does the job for now

**Comment by bobrik** [comment]
Thanks! It's will be ready on Docker Hub shortly.

**Pull request merged**
