### PR TITLE
Update to 4.2.1

### PR DESCRIPTION
**Pull request by jippi**

### CODE REVIEW

**Comment by bobrik** [comment]
Thanks! It's on Docker Hub now.

**Comment by jippi** [comment]
@bobrik thanks! i ended up rolling https://github.com/jippi/docker-elastic-curator while waiting.. if you want to cherry-pick it into this repo I can kill mine

The repo consist of a new Makefile to ease management, Dockerfile with curator env set, a docker entrypoint allowing you to run bash or arbitrary commands (e.g. 4.2.x have `curator` and `curator_cli` commands, which your Dockerfile don't allow me to run

**Comment by bobrik** [comment]
From the docs it seems that we may default to `curator_cli` instead of `curator` to get more universal docker-friendly image. Other than that I think it makes sense to cherry-pick your entrypoint. I'm still using v3.4.1 for my needs, so I may be wrong.

* https://www.elastic.co/guide/en/elasticsearch/client/curator/current/singleton-cli.html

@jippi, what do you think?

@untergeek, I see `Dockerfile` in the Curator repo, but there is no image on Docker Hub:

* https://hub.docker.com/u/elastic/

The official `Dockerfile` also produces much larger image: `python:2.7.8-slim` alone is 241.2MB, while my image is 48MB. What do you think about taking my image and supporting it?

**Comment by untergeek** [comment]
@bobrik 

Yes, the rebirth of `curator_cli` from the ashes of 3.x is to help with Docker and other VM scenarios where a YAML file might be hard to manage.

The `Dockerfile` is there, but I've never set out to publish an official image.  Now that Elastic is starting to provide official images for its products, Curator may surface there.  It's actually not in my control, so I'll have to talk to the infrastructure team that has been building, testing, and publishing the Docker images about that.

**Pull request merged**
